name: Gradle Test

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      
    - name: Test with Gradle
      run: ./gradlew test --no-daemon
      
    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-report
        path: app/build/reports/
        retention-days: 1
        overwrite: true
    

    - name: Check 100% Test Coverage
      run: |
        total=$(grep -A 1 "<counter type=\"INSTRUCTION\"" app/build/reports/jacoco/test/jacocoTestReport.xml | grep -o 'covered="[0-9]*"' | cut -d'"' -f2 | paste -sd+ - | bc)
        missed=$(grep -A 1 "<counter type=\"INSTRUCTION\"" app/build/reports/jacoco/test/jacocoTestReport.xml | grep -o 'missed="[0-9]*"' | cut -d'"' -f2 | paste -sd+ - | bc)
        coverage=$(echo "scale=2; 100 * $total / ($total + $missed)" | bc)
        echo "Coverage: $coverage%"
        if (( $(echo "$coverage < 100" | bc -l) )); then
          echo "Coverage is less than 100%"
          exit 1
        fi

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Test with Gradle
      run: ./gradlew build --no-daemon
