name: Gradle Test

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Test with Gradle
      run: ./gradlew test --no-daemon
    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-report
        path: app/build/reports/
        retention-days: 1
        overwrite: true

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build with Gradle
      run: ./gradlew build --no-daemon

  coverage:
    runs-on: ubuntu-latest 
    needs: test
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Generate Coverage Report
      run: ./gradlew jacocoTestReport --no-daemon

    - name: Verify Model Coverage Only
      run: ./gradlew checkModelCoverage --no-daemon
    - name: Upload JaCoCo Report HTML
      if: github.server_url == 'https://github.com'
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-html-report
        path: app/build/reports/jacoco/test/html/
