name: Gradle Test

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Test with Gradle
      run: ./gradlew test --no-daemon
    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-report
        path: app/build/reports/
        retention-days: 1
        overwrite: true

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Test with Gradle
      run: ./gradlew build --no-daemon

# This job runs after the test job
# and is used to generate a JaCoCo report
# and to enforce a minimum coverage rule
  coverage:
    runs-on: ubuntu-latest 
    # This job runs on the latest version of Ubuntu
    needs: test
    steps:
      - uses: actions/checkout@v4

      # sets up the JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      # initializes gradle
      # and caches dependencies
      # to speed up the build
      # process
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # generates jacoco report
      - name: Generate JaCoCo Report
        run: ./gradlew jacocoTestReport --no-daemon
      
      # uploads the jacoco report
      # to the GitHub actions
      # artifacts
      # so that it can be viewed
      # in the GitHub actions
      # UI
      - name: Upload JaCoCo Report
        if: github.server_url == 'https://github.co